os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="OpenSSL/1.0.2j"
    - CONAN_USERNAME="lasote"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=2
    - CONAN_STABLE_BRANCH_PATTERN="release/*"

  matrix:
    - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    
    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    
    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    
    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
    
    - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1

matrix:
   include:
       - os: osx 
         osx_image: xcode8.2 # apple-clang 8.2
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx 
         osx_image: xcode8.2 # apple-clang 8.2
         language: generic
         env: CONAN_CURRENT_PAGE=2
         
       - os: osx 
         osx_image: xcode8.1 # apple-clang 8.1
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx 
         osx_image: xcode8.1 # apple-clang 8.1
         language: generic
         env: CONAN_CURRENT_PAGE=2
         
       - os: osx 
         osx_image: xcode8 # apple-clang 8.0
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx 
         osx_image: xcode8 # apple-clang 8.0
         language: generic
         env: CONAN_CURRENT_PAGE=2
         
       - os: osx 
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx 
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env: CONAN_CURRENT_PAGE=2
         
       - os: osx 
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx 
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=2
     
       - os: osx
         osx_image: xcode6.4 # apple-clang 6.1
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode6.4 # apple-clang 6.1
         language: generic
         env: CONAN_CURRENT_PAGE=2
       
       - os: osx 
         osx_image: xcode6.2 # apple-clang 6.0
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx 
         osx_image: xcode6.2 # apple-clang 6.0
         language: generic
         env: CONAN_CURRENT_PAGE=2

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
