---
os: osx
language: generic

jobs:
  include:
    - name: "1.1.1c - XCode 7.3"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.1.1c"
    - name: "1.1.1c - XCode 8.3"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.1.1c"
    - name: "1.1.1c - XCode 9.2"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.1.1c"
    - name: "1.1.1c - XCode 9.4"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.1.1c"
    - name: "1.1.1c - XCode 10"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.1.1c"

    - name: "1.1.1b - XCode 7.3"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.1.1b"
    - name: "1.1.1b - XCode 8.3"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.1.1b"
    - name: "1.1.1b - XCode 9.2"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.1.1b"
    - name: "1.1.1b - XCode 9.4"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.1.1b"
    - name: "1.1.1b - XCode 10"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.1.1b"

    - name: "1.1.1a - XCode 7.3"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.1.1a"
    - name: "1.1.1a - XCode 8.3"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.1.1a"
    - name: "1.1.1a - XCode 9.2"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.1.1a"
    - name: "1.1.1a - XCode 9.4"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.1.1a"
    - name: "1.1.1a - XCode 10"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.1.1a"

    - name: "1.1.0k - XCode 7.3 - Page 1"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.1.0k" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0k - XCode 7.3 - Page 2"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.1.0k" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0k - XCode 8.3 - Page 1"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.1.0k" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0k - XCode 8.3 - Page 2"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.1.0k" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0k - XCode 9.2 - Page 1"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.1.0k" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0k - XCode 9.2 - Page 2"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.1.0k" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0k - XCode 9.4 - Page 1"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.1.0k" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0k - XCode 9.4 - Page 2"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.1.0k" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0k - XCode 10 - Page 1"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.1.0k" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0k - XCode 10 - Page 2"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.1.0k" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

    - name: "1.1.0j - XCode 7.3 - Page 1"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.1.0j" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0j - XCode 7.3 - Page 2"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.1.0j" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0j - XCode 8.3 - Page 1"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.1.0j" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0j - XCode 8.3 - Page 2"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.1.0j" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0j - XCode 9.2 - Page 1"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.1.0j" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0j - XCode 9.2 - Page 2"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.1.0j" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0j - XCode 9.4 - Page 1"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.1.0j" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0j - XCode 9.4 - Page 2"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.1.0j" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0j - XCode 10 - Page 1"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.1.0j" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0j - XCode 10 - Page 2"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.1.0j" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

    - name: "1.1.0i - XCode 7.3 - Page 1"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.1.0i" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0i - XCode 7.3 - Page 2"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.1.0i" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0i - XCode 8.3 - Page 1"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.1.0i" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0i - XCode 8.3 - Page 2"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.1.0i" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0i - XCode 9.2 - Page 1"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.1.0i" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0i - XCode 9.2 - Page 2"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.1.0i" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0i - XCode 9.4 - Page 1"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.1.0i" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0i - XCode 9.4 - Page 2"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.1.0i" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
    - name: "1.1.0i - XCode 10 - Page 1"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.1.0i" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - name: "1.1.0i - XCode 10 - Page 2"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.1.0i" CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

    - name: "1.0.2s - XCode 7.3"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.0.2s"
    - name: "1.0.2s - XCode 8.3"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.0.2s"
    - name: "1.0.2s - XCode 9.2"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.0.2s"
    - name: "1.0.2s - XCode 9.4"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.0.2s"
    - name: "1.0.2s - XCode 10"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.0.2s"

    - name: "1.0.2r - XCode 7.3"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.0.2r"
    - name: "1.0.2r - XCode 8.3"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.0.2r"
    - name: "1.0.2r - XCode 9.2"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.0.2r"
    - name: "1.0.2r - XCode 9.4"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.0.2r"
    - name: "1.0.2r - XCode 10"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.0.2r"

    - name: "1.0.2q - XCode 7.3"
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_REFERENCE="OpenSSL/1.0.2q"
    - name: "1.0.2q - XCode 8.3"
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_REFERENCE="OpenSSL/1.0.2q"
    - name: "1.0.2q - XCode 9.2"
      osx_image: xcode9.2
      env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_REFERENCE="OpenSSL/1.0.2q"
    - name: "1.0.2q - XCode 9.4"
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_REFERENCE="OpenSSL/1.0.2q"
    - name: "1.0.2q - XCode 10"
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_REFERENCE="OpenSSL/1.0.2q"

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
