---
os: osx
language: generic

env:
  global:
    - CONAN_TOTAL_PAGES: 2

builds: &builds
    name: "XCode 7.3 - Page 1"
    osx_image: xcode7.3
    env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 CONAN_REFERENCE="OpenSSL/${TRAVIS_BUILD_STAGE_NAME}"

    name: "XCode 7.3 - Page 2"
    osx_image: xcode7.3
    env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 CONAN_REFERENCE="OpenSSL/${TRAVIS_BUILD_STAGE_NAME}"

    name: "XCode 8.3 - Page 1"
    osx_image: xcode8.3
    env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 CONAN_REFERENCE="OpenSSL/${TRAVIS_BUILD_STAGE_NAME}"

    name: "XCode 8.3 - Page 2"
    osx_image: xcode8.3
    env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 CONAN_REFERENCE="OpenSSL/${TRAVIS_BUILD_STAGE_NAME}"

    name: "XCode 9.2 - Page 1"
    osx_image: xcode9.2
    env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 CONAN_REFERENCE="OpenSSL/${TRAVIS_BUILD_STAGE_NAME}"

    name: "XCode 9.2 - Page 2"
    osx_image: xcode9.2
    env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 CONAN_REFERENCE="OpenSSL/${TRAVIS_BUILD_STAGE_NAME}"

    name: "XCode 9.4 - Page 1"
    osx_image: xcode9.4
    env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 CONAN_REFERENCE="OpenSSL/${TRAVIS_BUILD_STAGE_NAME}"

    name: "XCode 9.4 - Page 1"
    osx_image: xcode9.4
    env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 CONAN_REFERENCE="OpenSSL/${TRAVIS_BUILD_STAGE_NAME}"

    name: "XCode 10 - Page 1"
    osx_image: xcode10
    env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 CONAN_REFERENCE="OpenSSL/${TRAVIS_BUILD_STAGE_NAME}"

    name: "XCode 10 - Page 1"
    osx_image: xcode10
    env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 CONAN_REFERENCE="OpenSSL/${TRAVIS_BUILD_STAGE_NAME}"

jobs:
  include:
    - stage: "1.1.1c"
      <<: *builds
    - stage: "1.1.1b"
      <<: *builds
    - stage: "1.1.1a"
      <<: *builds

    - stage: "1.1.0k"
      <<: *builds
    - stage: "1.1.0j"
      <<: *builds
    - stage: "1.1.0i"
      <<: *builds

    - stage: "1.0.2s"
      <<: *builds
    - stage: "1.0.2r"
      <<: *builds
    - stage: "1.0.2q"
      <<: *builds

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
